server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo:27017/admin?authSource=admin&retryWrites=true&w=majority
      database: client
      auto-index-creation: true

application:
  productService:
    url: product-service:8082

application-version: 1.0
