server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://admin:admin@127.0.0.1:27017/admin?authSource=admin&retryWrites=true&w=majority
        database: sales
        auto-index-creation: true

application:
  productService:
    url: http://localhost:8082
  clientService:
    url: http://localhost:8081
    searchClientEndpoint: ${application.clientService.url}/client/isRegistered/{id}

application-version: 1.0
